#ifndef OPENEVERYTHING_VERSION_H
#define OPENEVERYTHING_VERSION_H

#define OE_VERSION_NUMERIC 0,2,3,1
#define OE_VERSION_STRING "0.2.3 SP1"
#define OE_FILE_VERSION_STRING "0.2.3.1\0"
#define OE_PRODUCT_VERSION_STRING "0.2.3 SP1\0"
#define OE_VERSION_WSTRING L"0.2.3 SP1"

#endif
